import Link from "next/link";
import { ArrowRight, Clock3 } from "lucide-react";
import { BLOG_CATEGORY_LABELS, type BlogArticle } from "@/domain/entities/BlogArticle";

export function formatBlogDate(date: string) {
  return new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "long", year: "numeric" }).format(new Date(`${date}T00:00:00`));
}

export function BlogCard({ article, featured = false }: { article: BlogArticle; featured?: boolean }) {
  return <article className={`group overflow-hidden rounded-2xl border border-border-subtle bg-surface-container-lowest shadow-card transition-shadow hover:shadow-card-hover ${featured ? "grid md:grid-cols-2" : "flex flex-col"}`}><Link href={`/blog/${article.slug}`} aria-label={`Baca ${article.title}`} className={`relative block overflow-hidden bg-surface-container-low ${featured ? "min-h-72" : "aspect-[4/3]"}`}><div className="absolute inset-0 bg-cover bg-center transition-transform duration-700 group-hover:scale-105" style={{ backgroundImage: `url('${article.coverImageUrl}')` }} role="img" aria-label={article.coverImageAlt} /><div className="absolute inset-0 bg-gradient-to-t from-primary/25 to-transparent" /><span className="absolute left-5 top-5 rounded-full bg-surface-container-lowest/95 px-3 py-1.5 text-label-sm font-label-sm text-primary">{BLOG_CATEGORY_LABELS[article.category]}</span></Link><div className={`flex flex-1 flex-col ${featured ? "p-7 md:p-9" : "p-6"}`}><div className="flex items-center gap-3 text-label-sm text-on-surface-variant"><time dateTime={article.publishedAt}>{formatBlogDate(article.publishedAt)}</time><span aria-hidden="true">•</span><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" aria-hidden="true" />{article.readingMinutes} menit baca</span></div><h2 className={`mt-4 font-bold tracking-tight text-on-surface ${featured ? "text-3xl leading-tight" : "text-headline-sm font-headline-sm"}`}>{article.title}</h2><p className="mt-3 text-body-md leading-6 text-on-surface-variant">{article.excerpt}</p><Link href={`/blog/${article.slug}`} className="mt-6 inline-flex items-center gap-1 text-label-md font-label-md text-primary hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary">Baca artikel<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" aria-hidden="true" /></Link></div></article>;
}
