import type { Metadata } from "next";
import { LockKeyhole, ShieldCheck } from "lucide-react";

export const metadata: Metadata = {
  title: "Kebijakan Privasi | Kurata",
  description: "Kebijakan privasi Kurata mengenai pengumpulan, penggunaan, dan perlindungan data pribadi Anda.",
  alternates: { canonical: "/privasi" },
};

const SECTIONS = [
  { title: "Pendahuluan", paragraphs: ["Selamat datang di Kurata.", "Kurata (\"Kami\") berkomitmen untuk melindungi data pribadi setiap pengguna yang mengakses dan menggunakan website maupun aplikasi Kurata.", "Kebijakan Privasi ini menjelaskan bagaimana Kurata mengumpulkan, menggunakan, menyimpan, melindungi, serta mengungkapkan data pribadi pengguna sesuai dengan peraturan perundang-undangan yang berlaku di Republik Indonesia.", "Dengan menggunakan layanan Kurata, Anda menyatakan telah membaca, memahami, dan menyetujui Kebijakan Privasi ini."] },
  { title: "Data yang Kami Kumpulkan", groups: [{ label: "A. Data Identitas", points: ["Nama lengkap", "Alamat email", "Nomor telepon", "Foto profil"] }, { label: "B. Data Akun", points: ["Username", "Kata sandi (tersimpan dalam bentuk terenkripsi)", "Riwayat login", "Pengaturan akun"] }, { label: "C. Data Listing", intro: "Apabila Anda mengunggah listing tanah, kami dapat menyimpan:", points: ["Judul listing", "Lokasi", "Titik koordinat", "Luas tanah", "Harga", "Foto", "Video", "Deskripsi", "Dokumen pendukung yang Anda unggah"] }, { label: "D. Data Aktivitas", intro: "Kami dapat mencatat:", points: ["Halaman yang dikunjungi", "Riwayat pencarian", "Tanah favorit", "Riwayat chat", "Riwayat pertanyaan kepada broker"] }, { label: "E. Data Perangkat", intro: "Kami dapat mengumpulkan:", points: ["Alamat IP", "Jenis perangkat", "Sistem operasi", "Browser", "Informasi teknis lainnya yang diperlukan untuk keamanan layanan."] }] },
  { title: "Cara Kami Menggunakan Data", intro: "Data digunakan untuk:", points: ["Membuat akun pengguna.", "Mengelola akun.", "Menampilkan listing.", "Menghubungkan pembeli dengan broker atau pemilik tanah.", "Memberikan layanan pelanggan.", "Mengirim notifikasi.", "Meningkatkan kualitas layanan.", "Mencegah penyalahgunaan platform.", "Menjaga keamanan sistem.", "Memenuhi kewajiban hukum yang berlaku."] },
  { title: "Penggunaan Cookie", paragraphs: ["Kurata dapat menggunakan cookie dan teknologi serupa untuk:"], points: ["Mengingat preferensi pengguna.", "Menjaga sesi login.", "Menganalisis penggunaan website.", "Meningkatkan pengalaman pengguna.", "Menampilkan layanan yang lebih relevan."], outro: "Pengguna dapat mengatur penggunaan cookie melalui pengaturan browser masing-masing." },
  { title: "Penyimpanan dan Keamanan Data", paragraphs: ["Kurata menerapkan langkah-langkah teknis dan organisasi yang wajar untuk melindungi data pribadi dari:"], points: ["Akses tanpa izin.", "Penyalahgunaan.", "Kehilangan data.", "Perubahan tanpa hak.", "Pengungkapan yang tidak sah."], outro: "Meskipun demikian, tidak ada sistem elektronik yang dapat dijamin aman 100%, sehingga pengguna juga bertanggung jawab menjaga kerahasiaan akun dan kata sandinya." },
  { title: "Pengungkapan Data kepada Pihak Ketiga", paragraphs: ["Kurata tidak menjual data pribadi pengguna kepada pihak lain.", "Data pribadi dapat dibagikan apabila:"], points: ["Diperlukan untuk penyediaan layanan (misalnya layanan email, penyimpanan data, atau layanan teknis lainnya).", "Diperlukan untuk mematuhi kewajiban hukum.", "Diminta oleh instansi pemerintah atau aparat penegak hukum sesuai ketentuan yang berlaku.", "Pengguna memberikan persetujuan."] },
  { title: "Layanan Pihak Ketiga", paragraphs: ["Kurata dapat menggunakan layanan pihak ketiga seperti:"], points: ["Google Maps", "Google Login", "WhatsApp", "Layanan analitik", "Penyedia hosting dan cloud", "Penyedia notifikasi"], outro: "Penggunaan layanan tersebut tunduk pada kebijakan privasi masing-masing penyedia layanan." },
  { title: "Hak Pengguna", intro: "Pengguna berhak untuk:", points: ["Mengakses data pribadinya.", "Memperbarui informasi akun.", "Memperbaiki data yang tidak akurat.", "Menghapus akun sesuai ketentuan yang berlaku.", "Menarik persetujuan atas pemrosesan data apabila dimungkinkan berdasarkan hukum."] },
  { title: "Penghapusan Akun", paragraphs: ["Pengguna dapat mengajukan permohonan penghapusan akun melalui layanan pelanggan Kurata.", "Kurata dapat tetap menyimpan sebagian data apabila diwajibkan oleh hukum, diperlukan untuk penyelesaian sengketa, pencegahan penipuan, atau kepentingan keamanan sistem."] },
  { title: "Perlindungan Data Anak", paragraphs: ["Layanan Kurata ditujukan bagi pengguna yang telah memenuhi persyaratan usia sesuai hukum yang berlaku.", "Apabila diketahui terdapat data pribadi anak yang dikumpulkan tanpa persetujuan yang diperlukan menurut hukum, Kurata berhak mengambil langkah yang dianggap perlu, termasuk menghapus data tersebut."] },
  { title: "Perubahan Kebijakan Privasi", paragraphs: ["Kurata dapat mengubah Kebijakan Privasi ini dari waktu ke waktu.", "Perubahan akan diumumkan melalui website, aplikasi, atau media resmi Kurata dan mulai berlaku sejak tanggal yang ditetapkan."] },
  { title: "Hubungi Kami", paragraphs: ["Apabila Anda memiliki pertanyaan mengenai Kebijakan Privasi ini atau penggunaan data pribadi Anda, silakan menghubungi Kurata melalui halaman Hubungi Kami yang tersedia pada website resmi."] },
  { title: "Persetujuan", paragraphs: ["Dengan membuat akun, mengakses, atau menggunakan layanan Kurata, Anda menyatakan bahwa telah membaca, memahami, dan menyetujui Kebijakan Privasi ini serta memberikan persetujuan atas pemrosesan data pribadi sebagaimana dijelaskan dalam dokumen ini."] },
];

export default function PrivasiPage() {
  return <div className="min-h-screen bg-background pt-16 md:pt-20">
    <section className="bg-primary py-16 text-on-primary md:py-20"><div className="container-main max-w-4xl"><LockKeyhole className="h-9 w-9 text-on-primary-container" /><p className="mt-6 text-label-sm font-label-sm uppercase tracking-wider text-on-primary-container">Kurata</p><h1 className="mt-2 text-4xl font-bold tracking-tight md:text-5xl">Kebijakan Privasi</h1><p className="mt-4 max-w-2xl text-body-md leading-7 text-on-primary/80">Bagaimana Kurata mengumpulkan, menggunakan, menyimpan, melindungi, serta mengungkapkan data pribadi pengguna.</p><p className="mt-6 text-label-sm text-on-primary/70">Terakhir diperbarui: Agustus 2026</p></div></section>
    <main className="container-main max-w-4xl py-12 md:py-16"><div className="rounded-xl border border-primary/15 bg-primary/5 p-5 text-body-md leading-6 text-on-surface-variant"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-primary" /><p>Privasi dan keamanan data Anda penting bagi kami. Bacalah kebijakan ini untuk memahami cara kami memproses data pribadi Anda.</p></div></div><div className="mt-8 space-y-3">{SECTIONS.map((section, index) => <details key={section.title} className="rounded-xl border border-border-subtle bg-surface-container-lowest px-5 py-4 shadow-card" open={index === 0}><summary className="cursor-pointer text-label-md font-label-md text-on-surface">{index + 1}. {section.title}</summary><div className="space-y-3 pt-4 text-body-md leading-7 text-on-surface-variant">{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.intro ? <p>{section.intro}</p> : null}{section.points ? <ul className="list-disc space-y-1 pl-5">{section.points.map((point) => <li key={point}>{point}</li>)}</ul> : null}{section.groups?.map((group) => <div key={group.label}><h3 className="font-label-md text-on-surface">{group.label}</h3>{group.intro ? <p className="mt-2">{group.intro}</p> : null}<ul className="mt-2 list-disc space-y-1 pl-5">{group.points.map((point) => <li key={point}>{point}</li>)}</ul></div>)}{section.outro ? <p>{section.outro}</p> : null}</div></details>)}</div></main>
  </div>;
}
