import type { Metadata } from "next";
import Link from "next/link";
import { BadgeHelp, BookOpenCheck, BriefcaseBusiness, Building2, ChevronRight, CircleHelp, FileText, KeyRound, LockKeyhole, Search, ShieldCheck, UserRoundCheck } from "lucide-react";
import { SUPPORT_CATEGORIES_CONTENT, SUPPORT_CATEGORY_LABELS, SUPPORT_FAQS } from "@/application/config/supportContent";
import { SUPPORT_CATEGORIES, type SupportCategory } from "@/domain/entities/SupportRequest";
import { SupportRequestForm } from "@/presentation/components/support/SupportRequestForm";

export const metadata: Metadata = { title: "Pusat Bantuan | Kurata", description: "Temukan jawaban seputar akun, pencarian tanah, listing, layanan Kurata, investasi, broker, dan privasi data." };

const CATEGORY_ICONS: Record<SupportCategory, typeof CircleHelp> = { "account-security": KeyRound, "search-listings": Search, "listing-information": FileText, investment: Building2, "broker-partner": UserRoundCheck, "kurata-services": BriefcaseBusiness, "privacy-data": LockKeyhole };
const POPULAR_IDS = ["search-land", "listing-verification", "password-recovery", "investment-guidance"];
type SearchParams = { category?: string | string[]; q?: string | string[] };
function value(input: string | string[] | undefined) { return typeof input === "string" ? input : ""; }
function isSupportCategory(input: string): input is SupportCategory { return SUPPORT_CATEGORIES.includes(input as SupportCategory); }
function helpHref(category?: string, query?: string) { const params = new URLSearchParams(); if (category) params.set("category", category); if (query) params.set("q", query); const suffix = params.toString(); return `/bantuan${suffix ? `?${suffix}` : ""}`; }

export default async function HelpPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const params = await searchParams;
  const query = value(params.q).trim();
  const categoryValue = value(params.category);
  const category = isSupportCategory(categoryValue) ? categoryValue : undefined;
  const normalizedQuery = query.toLocaleLowerCase("id-ID");
  const faqs = SUPPORT_FAQS.filter((faq) => (!category || faq.category === category) && (!normalizedQuery || `${faq.question} ${faq.answer} ${SUPPORT_CATEGORY_LABELS[faq.category]}`.toLocaleLowerCase("id-ID").includes(normalizedQuery)));
  const popularFaqs = POPULAR_IDS.map((id) => SUPPORT_FAQS.find((faq) => faq.id === id)).filter((faq): faq is NonNullable<typeof faq> => Boolean(faq));
  return <div className="min-h-screen bg-background"><section className="bg-primary pb-16 pt-28 text-on-primary md:pb-20 md:pt-36"><div className="container-main text-center"><div className="mx-auto inline-flex items-center gap-2 rounded-full bg-on-primary/10 px-3 py-2 text-label-sm font-label-sm text-on-primary-container"><BadgeHelp className="h-4 w-4" aria-hidden="true" />Pusat Bantuan Kurata</div><h1 className="mx-auto mt-5 max-w-3xl text-4xl font-bold tracking-tight md:text-5xl">Ada yang Bisa Kami Bantu?</h1><p className="mx-auto mt-4 max-w-2xl text-body-md leading-7 text-on-primary/75 md:text-base">Temukan panduan untuk menggunakan Kurata, memahami informasi awal properti, dan menjaga data Anda tetap aman.</p><form method="get" className="mx-auto mt-8 flex max-w-2xl flex-col gap-3 rounded-2xl bg-surface-container-lowest p-2 shadow-card sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-outline" aria-hidden="true" /><input name="q" type="search" defaultValue={query} placeholder="Cari pertanyaan atau topik" aria-label="Cari pertanyaan atau topik bantuan" className="w-full rounded-xl bg-transparent py-3 pl-11 pr-4 text-body-md text-on-surface outline-none placeholder:text-outline" />{category && <input type="hidden" name="category" value={category} />}</div><button type="submit" className="rounded-xl bg-primary px-6 py-3 text-label-md font-label-md text-on-primary transition-colors hover:bg-primary/90">Cari Bantuan</button></form></div></section>
    {!category && !query && <section className="container-main py-12 md:py-16" aria-labelledby="popular-help-title"><div className="flex items-end justify-between gap-4"><div><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Topik populer</p><h2 id="popular-help-title" className="mt-2 text-3xl font-bold tracking-tight text-on-surface">Jawaban yang Sering Dicari</h2></div><BookOpenCheck className="hidden h-9 w-9 text-primary md:block" aria-hidden="true" /></div><div className="mt-8 grid gap-4 md:grid-cols-2">{popularFaqs.map((faq) => <Link key={faq.id} href="#faq" className="group rounded-2xl border border-border-subtle bg-surface-container-lowest p-6 shadow-card transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-card-hover"><p className="text-label-sm font-label-sm text-primary">{SUPPORT_CATEGORY_LABELS[faq.category]}</p><h3 className="mt-2 flex items-start justify-between gap-4 text-headline-sm font-headline-sm text-on-surface">{faq.question}<ChevronRight className="h-5 w-5 shrink-0 text-primary transition-transform group-hover:translate-x-1" aria-hidden="true" /></h3><p className="mt-3 line-clamp-2 text-body-md leading-6 text-on-surface-variant">{faq.answer}</p></Link>)}</div></section>}
    <section className="bg-surface-container-low py-16 md:py-20" aria-labelledby="help-category-title"><div className="container-main"><div className="max-w-2xl"><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Jelajahi bantuan</p><h2 id="help-category-title" className="mt-2 text-3xl font-bold tracking-tight text-on-surface">Pilih Topik yang Sesuai</h2></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{SUPPORT_CATEGORIES_CONTENT.map((item) => { const Icon = CATEGORY_ICONS[item.id]; return <Link key={item.id} href={helpHref(item.id, query)} className={`rounded-2xl border p-5 transition-all hover:-translate-y-0.5 ${category === item.id ? "border-primary bg-primary text-on-primary" : "border-border-subtle bg-surface-container-lowest text-on-surface hover:border-primary/30 hover:shadow-card"}`}><Icon className={`h-7 w-7 ${category === item.id ? "text-on-primary-container" : "text-primary"}`} aria-hidden="true" /><h3 className="mt-5 text-headline-sm font-headline-sm">{item.title}</h3><p className={`mt-2 text-body-md leading-6 ${category === item.id ? "text-on-primary/75" : "text-on-surface-variant"}`}>{item.description}</p></Link>})}</div></div></section>
    <section id="faq" className="container-main scroll-mt-24 py-16 md:py-20" aria-labelledby="faq-title"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Pertanyaan umum</p><h2 id="faq-title" className="mt-2 text-3xl font-bold tracking-tight text-on-surface">{category ? SUPPORT_CATEGORY_LABELS[category] : "Temukan Jawaban Anda"}</h2></div>{(category || query) && <Link href="/bantuan" className="text-label-md font-label-md text-primary hover:underline">Reset pencarian</Link>}</div><div className="mt-8 flex flex-wrap gap-2" aria-label="Filter kategori"><Link href={helpHref(undefined, query)} className={`rounded-full px-4 py-2 text-label-sm font-label-sm ${!category ? "bg-primary text-on-primary" : "bg-surface-container-low text-on-surface-variant hover:text-primary"}`}>Semua</Link>{SUPPORT_CATEGORIES.map((item) => <Link key={item} href={helpHref(item, query)} className={`rounded-full px-4 py-2 text-label-sm font-label-sm ${category === item ? "bg-primary text-on-primary" : "bg-surface-container-low text-on-surface-variant hover:text-primary"}`}>{SUPPORT_CATEGORY_LABELS[item]}</Link>)}</div>{faqs.length > 0 ? <div className="mt-8 grid gap-3 lg:grid-cols-2">{faqs.map((faq) => <details key={faq.id} className="group rounded-xl border border-border-subtle bg-surface-container-lowest px-5 py-4"><summary className="cursor-pointer list-none pr-8 text-label-md font-label-md text-on-surface">{faq.question}<span className="float-right -mr-7 text-xl text-primary transition-transform group-open:rotate-45" aria-hidden="true">+</span></summary><p className="pt-3 text-body-md leading-6 text-on-surface-variant">{faq.answer}</p></details>)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-outline-variant bg-surface-container-low p-10 text-center"><CircleHelp className="mx-auto h-9 w-9 text-primary" aria-hidden="true" /><h3 className="mt-4 text-headline-sm font-headline-sm text-on-surface">Jawaban belum ditemukan</h3><p className="mt-2 text-body-md text-on-surface-variant">Coba gunakan kata kunci lain atau kirim pertanyaan kepada tim Kurata.</p><a href="#kontak" className="mt-5 inline-flex text-label-md font-label-md text-primary hover:underline">Kirim pertanyaan</a></div>}</section>
    <section className="bg-primary py-14 text-on-primary md:py-16" aria-labelledby="account-help-title"><div className="container-main grid gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><LockKeyhole className="h-9 w-9 text-on-primary-container" aria-hidden="true" /><p className="mt-5 text-label-sm font-label-sm uppercase tracking-wider text-on-primary-container">Akun & keamanan</p><h2 id="account-help-title" className="mt-2 text-3xl font-bold tracking-tight">Butuh Bantuan Masuk?</h2><p className="mt-4 text-body-md leading-7 text-on-primary/75">Pemulihan password belum aktif karena autentikasi Kurata masih dalam mode pengembangan. Jangan membagikan password Anda kepada siapa pun, termasuk melalui formulir bantuan.</p></div><div className="rounded-2xl border border-on-primary/15 bg-on-primary/8 p-6"><h3 className="text-headline-sm font-headline-sm">Yang dapat dilakukan sekarang</h3><ul className="mt-5 space-y-3 text-body-md leading-6 text-on-primary/80"><li>• Pastikan Anda menggunakan email yang sama saat mendaftar.</li><li>• Kirim pertanyaan melalui formulir bantuan bila memerlukan tindak lanjut.</li><li>• Jangan kirim password lama, password baru, atau kode verifikasi.</li></ul></div></div></section>
    <section id="kontak" className="container-main scroll-mt-24 py-16 md:py-24" aria-labelledby="support-contact-title"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Hubungi kami</p><h2 id="support-contact-title" className="mt-2 text-3xl font-bold tracking-tight text-on-surface">Masih Membutuhkan Bantuan?</h2><p className="mt-4 text-body-md leading-7 text-on-surface-variant">Kirim konteks singkat mengenai pertanyaan atau kendala Anda. Tim Kurata akan menggunakan informasi ini untuk meninjau langkah berikutnya.</p><div className="mt-7 rounded-2xl border border-primary/15 bg-primary/5 p-6"><ShieldCheck className="h-7 w-7 text-primary" aria-hidden="true" /><h3 className="mt-4 text-headline-sm font-headline-sm text-on-surface">Jaga data Anda tetap aman</h3><p className="mt-2 text-body-md leading-6 text-on-surface-variant">Untuk tahap awal, cukup kirim informasi umum. Dokumen sensitif hanya boleh dibagikan melalui proses aman jika benar-benar dibutuhkan.</p></div></div><SupportRequestForm /></div></section>
  </div>;
}
