import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, BadgeCheck, Building2, ChartNoAxesCombined, FileSearch, MapPinned, Scale, ShieldCheck } from "lucide-react";
import { GetRecommendedProperties } from "@/application/use-cases/GetRecommendedProperties";
import { container } from "@/infrastructure/di/container";
import { PropertyCard } from "@/presentation/components/home/PropertyCard";
import { InvestmentInquiryForm } from "@/presentation/components/investment/InvestmentInquiryForm";

export const metadata: Metadata = { title: "Layanan Investasi Tanah | Kurata", description: "Eksplorasi peluang tanah dengan konteks lokasi, kebutuhan, dan langkah verifikasi yang lebih terarah bersama Kurata.", openGraph: { title: "Layanan Investasi Tanah | Kurata", description: "Mulai eksplorasi investasi tanah dengan informasi awal yang jelas dan bertanggung jawab." } };

const SERVICE_AREAS = [
  { Icon: MapPinned, title: "Pemetaan kebutuhan", description: "Susun tujuan, area, preferensi properti, serta kisaran anggaran sebagai titik awal eksplorasi." },
  { Icon: ChartNoAxesCombined, title: "Eksplorasi peluang", description: "Jelajahi listing dan konteks area yang dapat relevan dengan rencana Anda." },
  { Icon: FileSearch, title: "Tinjauan informasi awal", description: "Identifikasi informasi listing yang tersedia dan kebutuhan verifikasi sebelum keputusan lebih lanjut." },
  { Icon: Building2, title: "Arah langkah berikutnya", description: "Pahami peran profesional yang diperlukan dalam penilaian, legalitas, survei, dan transaksi." },
];

const PRINCIPLES = ["Tujuan dan jangka waktu investasi", "Lokasi, aksesibilitas, dan konteks kawasan", "Peruntukan serta informasi pertanahan yang tersedia", "Kesiapan verifikasi profesional dan transaksi"];

export default async function InvestmentPage() {
  const listings = (await new GetRecommendedProperties(container.propertyRepo).execute()).filter((property) => property.badge === "exclusive" || property.badge === "broker").slice(0, 3);
  return <div className="min-h-screen bg-background">
    <section className="overflow-hidden bg-surface-container-low pt-16 md:pt-20"><div className="container-main grid items-center gap-12 py-12 md:grid-cols-[1.05fr_0.95fr] md:py-20"><div><div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-2 text-label-sm font-label-sm text-primary"><ChartNoAxesCombined className="h-4 w-4" aria-hidden="true" />Layanan Investasi Tanah</div><h1 className="mt-5 max-w-xl text-4xl font-bold leading-[1.12] tracking-tight text-on-surface md:text-5xl">Eksplorasi Investasi Tanah dengan Lebih Terarah</h1><p className="mt-5 max-w-xl text-body-md leading-7 text-on-surface-variant md:text-base">Kurata membantu Anda menyusun konteks awal investasi tanah—mulai dari tujuan, area, hingga langkah verifikasi yang perlu disiapkan sebelum mengambil keputusan.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#konsultasi" className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 text-label-md font-label-md text-on-primary transition-colors hover:bg-primary/90">Konsultasi Investasi<ArrowDown className="h-4 w-4" aria-hidden="true" /></Link><Link href="#peluang" className="inline-flex items-center rounded-lg border border-primary px-6 py-3 text-label-md font-label-md text-primary transition-colors hover:bg-primary/5">Lihat Peluang Tanah</Link></div><p className="mt-5 text-label-sm leading-5 text-on-surface-variant">Bukan rekomendasi keuangan dan tidak menjanjikan imbal hasil investasi.</p></div><div className="relative mx-auto w-full max-w-md md:max-w-none"><div className="absolute -inset-6 rounded-full bg-primary/10 blur-3xl" aria-hidden="true" /><div className="relative overflow-hidden rounded-2xl bg-primary shadow-card"><Image src="/eksklusif.png" alt="Ilustrasi eksplorasi investasi tanah Kurata" width={1182} height={1182} priority className="aspect-square w-full object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-primary via-primary/75 to-transparent px-6 pb-6 pt-20 text-on-primary"><p className="text-label-sm font-label-sm uppercase tracking-wider text-on-primary-container">Mulai dari informasi</p><p className="mt-2 text-headline-sm font-headline-sm">Pertimbangkan lokasi, tujuan, dan proses verifikasi secara menyeluruh.</p></div></div></div></div></section>
    <section className="container-main py-16 md:py-24" aria-labelledby="investment-service-title"><div className="max-w-2xl"><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Ruang lingkup layanan</p><h2 id="investment-service-title" className="mt-2 text-3xl font-bold tracking-tight text-on-surface">Mulai dari Kejelasan Kebutuhan</h2><p className="mt-3 text-body-md leading-7 text-on-surface-variant">Kami membantu merapikan informasi dan mengarahkan eksplorasi awal. Keputusan investasi tetap memerlukan pertimbangan mandiri serta verifikasi yang sesuai.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{SERVICE_AREAS.map(({ Icon, title, description }, index) => <article key={title} className="rounded-2xl border border-border-subtle bg-surface-container-lowest p-6"><span className="text-label-sm font-label-sm text-primary">0{index + 1}</span><Icon className="mt-5 h-7 w-7 text-primary" aria-hidden="true" /><h3 className="mt-4 text-headline-sm font-headline-sm text-on-surface">{title}</h3><p className="mt-2 text-body-md leading-6 text-on-surface-variant">{description}</p></article>)}</div></section>
    <section className="bg-primary py-16 text-on-primary md:py-20" aria-labelledby="investment-process-title"><div className="container-main grid gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><p className="text-label-sm font-label-sm uppercase tracking-wider text-on-primary-container">Cara memulai</p><h2 id="investment-process-title" className="mt-2 text-3xl font-bold tracking-tight">Kerangka Eksplorasi yang Bertanggung Jawab</h2><p className="mt-4 text-body-md leading-7 text-on-primary/75">Investasi tanah tidak hanya tentang menemukan harga yang sesuai. Gunakan kerangka ini untuk menyiapkan pertanyaan yang lebih tepat sejak awal.</p></div><ol className="grid gap-3 sm:grid-cols-2">{PRINCIPLES.map((principle, index) => <li key={principle} className="flex gap-4 rounded-xl border border-on-primary/15 bg-on-primary/8 p-5"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-on-primary text-label-sm font-label-sm text-primary">{index + 1}</span><span className="text-body-md leading-6 text-on-primary/90">{principle}</span></li>)}</ol></div></section>
    <section id="peluang" className="container-main scroll-mt-24 py-16 md:py-24" aria-labelledby="investment-listing-title"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div className="max-w-2xl"><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Listing untuk dieksplorasi</p><h2 id="investment-listing-title" className="mt-2 text-3xl font-bold tracking-tight text-on-surface">Mulai dari Pilihan yang Tersedia</h2><p className="mt-3 text-body-md leading-7 text-on-surface-variant">Contoh listing berikut dapat menjadi titik awal eksplorasi. Ketersediaan dan informasi detail perlu dikonfirmasi sebelum keputusan dibuat.</p></div><Link href="/cari-tanah" className="inline-flex items-center gap-1 text-label-md font-label-md text-primary hover:underline">Lihat semua tanah<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div><div className="mt-10 grid gap-gutter md:grid-cols-2 lg:grid-cols-3">{listings.map((property) => <PropertyCard key={property.id} property={property} />)}</div></section>
    <section className="bg-surface-container-low py-16 md:py-20" aria-labelledby="investment-boundaries-title"><div className="container-main grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Batasan penting</p><h2 id="investment-boundaries-title" className="mt-2 text-3xl font-bold tracking-tight text-on-surface">Keputusan Tetap Ada di Tangan Anda</h2><p className="mt-4 text-body-md leading-7 text-on-surface-variant">Kurata membantu konteks dan arah eksplorasi awal. Kami tidak memberikan nasihat keuangan personal, penilaian resmi, pendapat hukum, atau jaminan hasil investasi.</p></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl bg-surface-container-lowest p-6"><Scale className="h-7 w-7 text-primary" aria-hidden="true" /><h3 className="mt-4 text-headline-sm font-headline-sm text-on-surface">Verifikasi profesional</h3><p className="mt-2 text-body-md leading-6 text-on-surface-variant">Libatkan notaris/PPAT, surveyor, penasihat hukum, dan penilai berlisensi sesuai kebutuhan Anda.</p></article><article className="rounded-2xl bg-surface-container-lowest p-6"><ShieldCheck className="h-7 w-7 text-primary" aria-hidden="true" /><h3 className="mt-4 text-headline-sm font-headline-sm text-on-surface">Tidak ada janji hasil</h3><p className="mt-2 text-body-md leading-6 text-on-surface-variant">Nilai, likuiditas, dan hasil investasi dapat berubah. Selalu lakukan penilaian risiko secara mandiri.</p></article></div></div></section>
    <section id="konsultasi" className="container-main scroll-mt-24 py-16 md:py-24" aria-labelledby="investment-inquiry-title"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Konsultasi awal</p><h2 id="investment-inquiry-title" className="mt-2 text-3xl font-bold tracking-tight text-on-surface">Ceritakan Arah Investasi Anda</h2><p className="mt-4 text-body-md leading-7 text-on-surface-variant">Bagikan kebutuhan umum Anda untuk membantu Kurata mengarahkan eksplorasi berikutnya.</p><div className="mt-7 rounded-2xl bg-primary p-6 text-on-primary"><BadgeCheck className="h-8 w-8 text-on-primary-container" aria-hidden="true" /><h3 className="mt-4 text-headline-sm font-headline-sm">Mulai dengan data seperlunya</h3><p className="mt-2 text-body-md leading-6 text-on-primary/80">Jangan kirim nomor identitas, sertifikat, atau dokumen sensitif pada tahap konsultasi awal.</p></div></div><InvestmentInquiryForm /></div></section>
  </div>;
}
