const TERMS = [
  { title: "Pendahuluan", paragraphs: ["Selamat datang di Kurata.", "Kurata adalah platform digital yang mempertemukan pemilik tanah, mitra, investor, dan calon pembeli untuk memudahkan pemasaran serta pencarian tanah di Indonesia.", "Dengan mendaftar dan menggunakan layanan Kurata sebagai Mitra, Anda menyatakan telah membaca, memahami, dan menyetujui seluruh Syarat dan Ketentuan Kemitraan Mitra Kurata."] },
  { title: "Persyaratan Menjadi Mitra", intro: "Untuk menjadi Mitra Kurata, calon Mitra wajib memenuhi persyaratan berikut:", points: ["Berusia minimal 18 tahun.", "Memiliki identitas diri (KTP/Paspor/KITAS) yang masih berlaku.", "Memiliki nomor telepon dan alamat email aktif.", "Mengisi data diri secara lengkap dan benar.", "Memiliki rekening bank atas nama sendiri untuk keperluan pembayaran komisi (apabila berlaku).", "Bersedia mengikuti proses verifikasi yang dilakukan Kurata."], paragraphs: ["Kurata berhak menolak, menunda, atau membatalkan pendaftaran apabila ditemukan data yang tidak benar atau tidak memenuhi persyaratan."] },
  { title: "Status Mitra", paragraphs: ["Mitra merupakan mitra independen yang menggunakan platform Kurata untuk memasarkan tanah.", "Hubungan antara Kurata dan Mitra bukan merupakan hubungan kerja, kepegawaian, kemitraan usaha bersama, waralaba, ataupun hubungan hukum lainnya selain sebagai pengguna layanan platform."] },
  { title: "Kewajiban Mitra", intro: "Mitra wajib:", points: ["Memberikan informasi yang benar mengenai objek tanah.", "Memastikan memiliki izin atau kewenangan untuk memasarkan tanah yang diunggah.", "Menjaga etika dan profesionalisme.", "Memberikan pelayanan yang baik kepada calon pembeli.", "Memperbarui informasi apabila terdapat perubahan harga, luas, atau status tanah.", "Mematuhi seluruh peraturan perundang-undangan yang berlaku."] },
  { title: "Standar Listing", intro: "Mitra wajib memastikan setiap listing memuat informasi yang akurat, antara lain:", points: ["Lokasi tanah.", "Luas tanah.", "Harga.", "Status kepemilikan (sesuai informasi yang dimiliki).", "Foto asli objek.", "Deskripsi yang tidak menyesatkan."], paragraphs: ["Kurata berhak menghapus, menyembunyikan, atau menolak listing yang tidak memenuhi standar."] },
  { title: "Larangan", intro: "Mitra dilarang:", points: ["Mengunggah informasi palsu.", "Menggunakan identitas orang lain.", "Mengunggah foto yang bukan miliknya tanpa izin.", "Melakukan spam.", "Menyebarkan konten yang melanggar hukum.", "Menggunakan akun milik orang lain.", "Melakukan tindakan yang dapat merugikan pengguna lain maupun Kurata."] },
  { title: "Tanggung Jawab Mitra", intro: "Mitra bertanggung jawab penuh atas:", points: ["Seluruh informasi yang diunggah.", "Komunikasi dengan pemilik tanah.", "Komunikasi dengan calon pembeli.", "Proses negosiasi.", "Kesepakatan yang dibuat dengan para pihak.", "Segala tindakan yang dilakukan di luar platform Kurata."], paragraphs: ["Mitra wajib bertindak dengan itikad baik dan mematuhi hukum yang berlaku."] },
  { title: "Batas Tanggung Jawab Kurata", paragraphs: ["Kurata merupakan penyedia platform digital yang mempertemukan pengguna.", "Kurata bukan pemilik tanah, bukan broker properti, bukan kuasa penjual, dan bukan pihak dalam proses negosiasi maupun transaksi antara Mitra, pemilik tanah, dan calon pembeli."], intro: "Kurata tidak bertanggung jawab atas:", points: ["Keakuratan informasi yang diberikan oleh Mitra.", "Negosiasi harga.", "Pembayaran antar pihak.", "Isi perjanjian jual beli.", "Kerugian yang timbul akibat tindakan Mitra, pemilik tanah, maupun calon pembeli."], outro: "Pengguna tetap bertanggung jawab melakukan pemeriksaan dan verifikasi sebelum mengambil keputusan dalam bertransaksi." },
  { title: "Dugaan Penipuan atau Pelanggaran", intro: "Apabila Kurata menerima laporan mengenai dugaan pelanggaran yang dilakukan oleh Mitra, Kurata berhak:", points: ["Meminta klarifikasi dan dokumen pendukung.", "Melakukan proses verifikasi.", "Menangguhkan sementara akun selama proses pemeriksaan.", "Menghapus listing yang dianggap bermasalah.", "Memberikan peringatan tertulis.", "Menonaktifkan akun secara permanen apabila terbukti terjadi pelanggaran terhadap ketentuan platform."], paragraphs: ["Apabila ditemukan dugaan tindak pidana, Kurata berhak bekerja sama dengan pihak berwenang sesuai ketentuan hukum yang berlaku."] },
  { title: "Sistem Penilaian Mitra", intro: "Kurata dapat memberikan penilaian terhadap Mitra berdasarkan:", points: ["Kelengkapan data listing.", "Kecepatan merespons calon pembeli.", "Kepatuhan terhadap aturan.", "Kualitas pelayanan.", "Riwayat pelanggaran."], paragraphs: ["Kurata berhak menggunakan penilaian tersebut untuk menentukan prioritas penayangan listing maupun program penghargaan bagi Mitra."] },
  { title: "Komisi", paragraphs: ["Ketentuan mengenai komisi mengikuti kebijakan Kurata dan/atau kesepakatan yang berlaku pada setiap transaksi atau program kerja sama."] },
  { title: "Akun Mitra", paragraphs: ["Mitra bertanggung jawab menjaga keamanan akun."], intro: "Mitra dilarang:", points: ["Meminjamkan akun kepada pihak lain.", "Menjual akun.", "Mengalihkan akses akun tanpa izin Kurata."], outro: "Seluruh aktivitas yang dilakukan melalui akun menjadi tanggung jawab pemilik akun." },
  { title: "Kekayaan Intelektual", paragraphs: ["Seluruh hak atas nama, logo, desain, sistem, merek, dan konten milik Kurata merupakan kekayaan intelektual Kurata dan tidak boleh digunakan tanpa izin tertulis."] },
  { title: "Perubahan Ketentuan", paragraphs: ["Kurata dapat mengubah Syarat dan Ketentuan ini sewaktu-waktu. Perubahan akan diumumkan melalui website, aplikasi, atau media resmi Kurata dan berlaku sejak tanggal yang ditetapkan."] },
  { title: "Hukum yang Berlaku", paragraphs: ["Syarat dan Ketentuan ini diatur dan ditafsirkan berdasarkan hukum Republik Indonesia.", "Apabila terjadi perselisihan, para pihak akan mengutamakan penyelesaian secara musyawarah. Apabila tidak tercapai kesepakatan, penyelesaian dilakukan sesuai ketentuan hukum yang berlaku di Republik Indonesia."] },
  { title: "Persetujuan", intro: "Dengan mendaftar sebagai Mitra Kurata, pengguna menyatakan bahwa:", points: ["Seluruh data yang diberikan adalah benar.", "Telah membaca dan memahami seluruh Syarat dan Ketentuan.", "Bersedia mematuhi seluruh kebijakan Kurata.", "Bertanggung jawab atas setiap aktivitas yang dilakukan melalui akun Mitra Kurata."] },
];

export function BrokerTerms() {
  return <section id="syarat-ketentuan" className="scroll-mt-24 bg-surface-container-low py-16 md:py-20" aria-labelledby="terms-title"><div className="container-main max-w-4xl"><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Kemitraan Mitra Kurata</p><h2 id="terms-title" className="mt-2 text-3xl font-bold text-on-surface">Syarat dan Ketentuan</h2><p className="mt-3 text-body-md text-on-surface-variant">Terakhir diperbarui: Agustus 2026</p><div className="mt-8 space-y-3">{TERMS.map((term, index) => <details key={term.title} className="rounded-xl border border-border-subtle bg-surface-container-lowest px-5 py-4 shadow-card"><summary className="cursor-pointer text-label-md font-label-md text-on-surface">{index + 1}. {term.title}</summary><div className="space-y-3 pt-4 text-body-md leading-7 text-on-surface-variant">{term.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{term.intro ? <p>{term.intro}</p> : null}{term.points ? <ul className="list-disc space-y-1 pl-5">{term.points.map((point) => <li key={point}>{point}</li>)}</ul> : null}{term.outro ? <p>{term.outro}</p> : null}</div></details>)}</div></div></section>;
}
