"use client";

import { useState } from "react";
import { CheckCircle2, FileCheck2, LoaderCircle, ShieldCheck } from "lucide-react";

export function BrokerAssetForm() {
  const [submitted, setSubmitted] = useState(false);
  const [pending, setPending] = useState(false);
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); window.setTimeout(() => { setPending(false); setSubmitted(true); }, 500); }
  if (submitted) return <div className="rounded-2xl border border-primary/20 bg-primary/5 p-8 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-primary" /><h2 className="mt-4 text-2xl font-bold text-on-surface">Aset telah diajukan</h2><p className="mx-auto mt-3 max-w-lg text-body-md leading-6 text-on-surface-variant">Listing masuk ke antrean peninjauan Kurata. Aset tidak akan tampil di halaman publik sampai disetujui oleh admin.</p></div>;
  return <form onSubmit={submit} className="rounded-2xl border border-border-subtle bg-surface-container-lowest p-6 shadow-card md:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Judul aset" name="title" placeholder="Contoh: Tanah komersial akses tol" required /><Field label="Lokasi" name="location" placeholder="Kecamatan, kota" required /><Field label="Harga penawaran" name="price" placeholder="Contoh: Rp 1.500.000.000" required /><Field label="Luas tanah" name="area" placeholder="Contoh: 1.000 m²" required /><label className="text-label-md font-label-md text-on-surface">Jenis sertifikat<select required defaultValue="" className="mt-2 w-full rounded-lg border border-border-subtle px-3 py-2.5 text-body-md outline-none focus:border-primary"><option value="" disabled>Pilih sertifikat</option><option>SHM</option><option>HGB</option><option>HGU</option><option>HP</option></select></label><Field label="Tautan foto utama" name="image" type="url" placeholder="https://..." required /></div><label className="mt-5 block text-label-md font-label-md text-on-surface">Keterangan aset<textarea required name="description" rows={5} className="mt-2 w-full rounded-lg border border-border-subtle px-3 py-2.5 text-body-md outline-none focus:border-primary" placeholder="Jelaskan akses, kondisi tanah, dan informasi penting lain secara akurat." /></label><label className="mt-6 flex items-start gap-3 text-body-md leading-6 text-on-surface-variant"><input required type="checkbox" className="mt-1 h-4 w-4" /><span>Saya menyatakan informasi listing ini akurat dan bersedia menindaklanjuti permintaan perbaikan dari tim Kurata.</span></label><div className="mt-7 border-t border-border-subtle pt-5"><button disabled={pending} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-label-md font-label-md text-on-primary disabled:opacity-70">{pending ? <><LoaderCircle className="h-4 w-4 animate-spin" />Mengajukan aset...</> : <><FileCheck2 className="h-4 w-4" />Ajukan untuk verifikasi</>}</button><p className="mt-4 flex gap-2 text-label-sm leading-5 text-on-surface-variant"><ShieldCheck className="h-4 w-4 shrink-0 text-primary" />Aset yang diajukan akan diperiksa sebelum dipublikasikan.</p></div></form>;
}

function Field({ label, name, type = "text", placeholder, required }: { label: string; name: string; type?: string; placeholder: string; required?: boolean }) { return <label className="text-label-md font-label-md text-on-surface">{label}<input name={name} type={type} placeholder={placeholder} required={required} className="mt-2 w-full rounded-lg border border-border-subtle px-3 py-2.5 text-body-md font-normal outline-none placeholder:text-outline focus:border-primary" /></label>; }
