import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, Heart, MessageSquare, ShieldCheck } from "lucide-react";
import { WorkspaceLayout } from "@/presentation/components/workspace/WorkspaceLayout";
import { StatusPill } from "@/presentation/components/workspace/StatusPill";
import { GetUserWorkspace } from "@/application/use-cases/GetUserWorkspace";
import { container } from "@/infrastructure/di/container";
import { getCurrentAuthContext } from "@/infrastructure/security/authorization-dal";
import type { WorkspaceStatus } from "@/application/config/workspaceDemoData";

export default async function UserDashboardPage() {
  const auth = await getCurrentAuthContext();
  if (!auth) redirect("/masuk");

  const workspace = await new GetUserWorkspace(container.workspaceRepo).execute(auth.userId, auth.email);

  return <WorkspaceLayout kind="user" title={`Halo, ${workspace.name.split(" ")[0]}`} description="Pantau verifikasi akun, properti tersimpan, dan perkembangan pertanyaan Anda."><section className="rounded-2xl bg-primary p-6 text-on-primary md:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-label-sm font-label-sm uppercase tracking-wider text-on-primary-container">Status akun</p><h2 className="mt-2 text-2xl font-bold">Profil Anda sedang ditinjau</h2><p className="mt-2 max-w-xl text-body-md leading-6 text-on-primary/80">Tim Kurata sedang memeriksa data profil Anda. Kami akan memberi tahu bila ada informasi yang perlu dilengkapi.</p></div><Link href="/dashboard/verification" className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-label-md font-label-md text-primary sm:w-fit">Lihat status <ArrowRight className="h-4 w-4" /></Link></div></section><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Card icon={ShieldCheck} title="Verifikasi akun" value={<StatusPill status={workspace.verification as WorkspaceStatus} />} href="/dashboard/verification" /><Card icon={Heart} title="Properti tersimpan" value={`${workspace.favoriteProperties.length} aset`} href="/dashboard/favorites" /><Card icon={MessageSquare} title="Pertanyaan aktif" value={`${workspace.inquiries.length} percakapan`} href="/dashboard/inquiries" /></div><section className="mt-7 rounded-2xl border border-border-subtle bg-surface-container-lowest p-6 shadow-card"><div className="flex items-center justify-between"><div><p className="text-label-sm font-label-sm uppercase tracking-wider text-primary">Aktivitas terbaru</p><h2 className="mt-2 text-xl font-bold text-on-surface">Pertanyaan Anda</h2></div><Link href="/dashboard/inquiries" className="text-label-sm font-label-sm text-primary hover:underline">Lihat semua</Link></div><div className="mt-5 divide-y divide-border-subtle">{workspace.inquiries.map((inquiry) => <div key={inquiry.id} className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-label-md font-label-md text-on-surface">{inquiry.title}</p><p className="mt-1 text-label-sm text-on-surface-variant">{inquiry.broker} · {inquiry.updatedAt}</p></div><span className="w-fit rounded-full bg-blue-100 px-3 py-1 text-label-sm text-blue-800">{inquiry.status}</span></div>)}</div></section></WorkspaceLayout>;
}
function Card({ icon: Icon, title, value, href }: { icon: typeof ShieldCheck; title: string; value: React.ReactNode; href: string }) { return <Link href={href} className="rounded-2xl border border-border-subtle bg-surface-container-lowest p-5 shadow-card transition-transform hover:-translate-y-0.5"><Icon className="h-6 w-6 text-primary" /><p className="mt-5 text-label-md font-label-md text-on-surface">{title}</p><div className="mt-2 text-2xl font-bold text-on-surface">{value}</div></Link>; }
