"use client";

import { useActionState, type InputHTMLAttributes } from "react";
import { CheckCircle2, LoaderCircle, ShieldCheck } from "lucide-react";
import { INITIAL_INVESTMENT_INQUIRY_STATE } from "@/application/dto/InvestmentInquiryDTO";
import { INVESTMENT_HORIZONS, INVESTMENT_OBJECTIVES, INVESTMENT_PROPERTY_PREFERENCES } from "@/domain/entities/InvestmentInquiry";
import { submitInvestmentInquiry } from "@/app/investasi/actions";
import { SelectInput, TextInput } from "@/presentation/components/shared/FormField";

const OBJECTIVE_LABELS = { "capital-appreciation": "Potensi kenaikan nilai", development: "Pengembangan properti", "land-banking": "Simpan aset tanah", diversification: "Diversifikasi aset" };
const HORIZON_LABELS = { "less-than-1-year": "Kurang dari 1 tahun", "1-to-3-years": "1–3 tahun", "3-to-5-years": "3–5 tahun", "more-than-5-years": "Lebih dari 5 tahun" };
const PREFERENCE_LABELS = { "residential-land": "Tanah hunian", "commercial-land": "Tanah komersial", "industrial-land": "Tanah industri", "agricultural-land": "Tanah pertanian", "still-exploring": "Masih mengeksplorasi" };

export function InvestmentInquiryForm() {
  const [state, formAction, pending] = useActionState(submitInvestmentInquiry, INITIAL_INVESTMENT_INQUIRY_STATE);
  const errors = state.fieldErrors ?? {};

  if (state.status === "success") return <div className="rounded-2xl border border-primary/20 bg-primary/5 p-8 text-center" role="status"><CheckCircle2 className="mx-auto h-12 w-12 text-primary" aria-hidden="true" /><h3 className="mt-4 text-headline-md font-headline-md text-on-surface">Permintaan diterima</h3><p className="mt-3 text-body-md leading-6 text-on-surface-variant">{state.message}</p><p className="mt-4 text-label-md font-label-md text-primary">Referensi: {state.reference}</p><p className="mt-5 text-label-sm leading-5 text-on-surface-variant">Permintaan Anda telah tersimpan. Tim Kurata akan menghubungi Anda untuk langkah eksplorasi.</p></div>;

  return <form action={formAction} className="rounded-2xl border border-border-subtle bg-surface-container-lowest p-6 shadow-card sm:p-8"><input type="text" name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true" /><div><h3 className="text-headline-md font-headline-md text-on-surface">Ceritakan Rencana Potensi Lahan Anda</h3><p className="mt-2 text-body-md leading-6 text-on-surface-variant">Berikan konteks awal agar Kurata dapat mengarahkan langkah eksplorasi yang relevan.</p></div>{state.status === "error" && <p className="mt-5 rounded-lg bg-error-container px-4 py-3 text-body-md text-on-error-container" role="alert">{state.message}</p>}
    <div className="mt-7 grid gap-5 sm:grid-cols-2"><TextField id="fullName" name="fullName" label="Nama lengkap" autoComplete="name" required error={errors.fullName} /><TextField id="email" name="email" label="Email" type="email" autoComplete="email" required error={errors.email} /><TextField id="phone" name="phone" label="Nomor WhatsApp" type="tel" autoComplete="tel" inputMode="tel" required error={errors.phone} /><TextField id="area" name="area" label="Area yang diminati" placeholder="Contoh: Badung, Bali" required error={errors.area} /></div>
    <div className="mt-5 grid gap-5 sm:grid-cols-2"><TextField id="budget" name="budget" label="Kisaran anggaran" placeholder="Contoh: Rp2–3 miliar" required error={errors.budget} /><SelectField id="objective" name="objective" label="Tujuan investasi" required error={errors.objective} options={INVESTMENT_OBJECTIVES.map((value) => ({ value, label: OBJECTIVE_LABELS[value] }))} /></div>
    <div className="mt-5 grid gap-5 sm:grid-cols-2"><SelectField id="horizon" name="horizon" label="Jangka waktu" required error={errors.horizon} options={INVESTMENT_HORIZONS.map((value) => ({ value, label: HORIZON_LABELS[value] }))} /><SelectField id="propertyPreference" name="propertyPreference" label="Preferensi properti" required error={errors.propertyPreference} options={INVESTMENT_PROPERTY_PREFERENCES.map((value) => ({ value, label: PREFERENCE_LABELS[value] }))} /></div>
    <div className="mt-5"><label htmlFor="notes" className="text-label-md font-label-md text-on-surface">Catatan tambahan <span className="font-normal text-on-surface-variant">(opsional)</span></label><p className="mt-1 text-label-sm text-on-surface-variant">Jangan sertakan nomor identitas, sertifikat, atau dokumen sensitif.</p><textarea id="notes" name="notes" rows={4} maxLength={1000} aria-invalid={Boolean(errors.notes)} aria-describedby={errors.notes ? "notes-error" : undefined} className="mt-2 w-full resize-y rounded-lg border border-border-subtle bg-surface-container-lowest px-3 py-2.5 text-body-md text-on-surface outline-none placeholder:text-outline focus:border-primary focus:ring-2 focus:ring-primary/20 aria-[invalid=true]:border-error" placeholder="Contoh: Saya mempertimbangkan tanah dekat akses utama untuk rencana pengembangan jangka menengah." />{errors.notes && <p id="notes-error" className="mt-1.5 text-label-sm text-error" role="alert">{errors.notes}</p>}</div>
    <label className="mt-6 flex cursor-pointer items-start gap-3 text-body-md leading-6 text-on-surface-variant"><input type="checkbox" name="acceptedTerms" className="mt-1 h-4 w-4 shrink-0 rounded border-outline text-primary focus:ring-primary" /><span>Saya menyetujui data ini digunakan untuk menindaklanjuti konsultasi investasi awal dan memahami bahwa Kurata tidak menjanjikan hasil atau imbal hasil investasi.</span></label>{errors.acceptedTerms && <p className="mt-1.5 text-label-sm text-error" role="alert">{errors.acceptedTerms}</p>}
    <div className="mt-7 border-t border-border-subtle pt-6"><button type="submit" disabled={pending} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-6 py-3 text-label-md font-label-md text-on-primary transition-colors hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-65">{pending ? <><LoaderCircle className="h-4 w-4 animate-spin" aria-hidden="true" />Mengirim permintaan...</> : "Kirim Permintaan Konsultasi"}</button><div className="mt-4 flex items-start gap-2 text-label-sm leading-5 text-on-surface-variant"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true" />Informasi awal bukan rekomendasi keuangan, penilaian resmi, atau jaminan hasil investasi.</div></div>
  </form>;
}

function TextField({ id, name, label, type = "text", error, ...props }: { id: string; name: string; label: string; type?: string; error?: string } & InputHTMLAttributes<HTMLInputElement>) { return <TextInput id={id} name={name} label={label} type={type} error={error} {...props} />; }

function SelectField({ id, name, label, options, error, required }: { id: string; name: string; label: string; options: { value: string; label: string }[]; error?: string; required?: boolean }) { return <SelectInput id={id} name={name} label={label} options={options} error={error} required={required} />; }
